### PR TITLE
Task Completed

### PR DESCRIPTION
**Pull request by AdityaPratapSinghR**
Created an app using github API.
WhatsApp Image 2024-07-31 at 4 39 15 PM
WhatsApp Image 2024-07-31 at 4 39 14 PM (2)
WhatsApp Image 2024-07-31 at 4 39 14 PM (1)
WhatsApp Image 2024-07-31 at 4 39 14 PM

https://github.com/user-attachments/assets/eca97548-8292-47ca-8722-1b9f7a724bee

### CODE REVIEW

**Comment by tanay4768** [comment]
All checks cleared. Nice work.

**Comment by tanay4768** [comment]
Kindly sync your branch.

**Comment by AdityaPratapSinghR** [comment]
I have synced the follower branch.

**Comment by Priiiiyanshi** [comment]
Amazing work!! 👏🏻👏🏻👏🏻

**Pull request merged**
