### PR TITLE
Gaurav github_follower_fetcher

### PR DESCRIPTION
**Pull request by gaurav-33**
I have completed the task with all the folder structure mentioned in Task3.

🔽demo image and video 🔽

https://github.com/dev04sa/FlutterTeam_Tasks/assets/164652539/8fbd65ed-46ea-4d17-a59c-e225e72d8129

Screenshot_2024-07-10-10-16-08-59_2e8450f59f4a8792039dc7886ee5cfeb

Screenshot_2024-07-10-10-17-08-56_2e8450f59f4a8792039dc7886ee5cfeb

### CODE REVIEW

**Comment by tanay4768** [comment]
Kindly sync your branch please.

**Comment by gaurav-33** [comment]
> Kindly sync your branch please.
done

**Comment by Priiiiyanshi** [comment]
Great job on the code refactoring!! The structure of the entire code makes it easy to understand and readable. Moreover the usage of custom theme is excellent. Nice work!!

**Comment by tanay4768** [comment]
Great Work ! Providing us insight about writing clean code and saving time by defining color data first.

**Comment by gaurav-33** [comment]
> Great Work ! Providing us insight about writing clean code and saving time by defining color data first.

Thanks....we will learn through each other's code.

**Comment by gaurav-33** [comment]
> Great job on the code refactoring!! The structure of the entire code makes it easy to understand and readable. Moreover the usage of custom theme is excellent. Nice work!!

Thankyou for this review

**Pull request merged**
