### PR TITLE
FlutterTeam_Task1(crud)_Gaurav

### PR DESCRIPTION
**Pull request by gaurav-33**
this time corrected all the mesh.

A Basic Firebase FireStore CRUD application which deals with Students Information like Name, Student Id, Student Program, Cgpa.
Also Login/SignUp added using Firebase Authentication.

Attached Files - Screenshot and Video Demo.

Screenshot_2024-05-23-10-36-58-97_628fb5d708fa8f5cac3192221449a027

https://github.com/gaurav-33/FlutterTeam_Tasks/assets/164652539/25b7acdb-3584-4b3e-b801-1d55ed658a4d

### CODE REVIEW

**Comment by dev04sa** [comment]
@gaurav-33 ,same mistake again . can u please justify what I have told you earlier.
your app should run on any program. but still you have done only for android.

**Comment by gaurav-33** [comment]
> @gaurav-33 ,same mistake again . can u please justify what I have told you earlier. your app should run on any program. but still you have done only for android.

i have connected it for all platforms
image

**Comment by dev04sa** [comment]
Then why other folders are missing.  If u not push those folders as well.  Then your code is work in only your system. Try to correct it.

**Comment by gaurav-33** [comment]
> Then why other folders are missing. If u not push those folders as well. Then your code is work in only your system. Try to correct it.

ok sir Got it

**Pull request closed without merging**
