### PR TITLE
Tanay

### PR DESCRIPTION
**Pull request by tanay4768**
Screenshot 2024-05-25 234941

https://github.com/dev04sa/FlutterTeam_Tasks/assets/158015686/25cfeab5-dc32-4f4e-b804-2a2ab58fae9a

### CODE REVIEW

**Comment by dev04sa** [comment]
@tanay4768 , git pull the changes. 
because structure is updated .

**Comment by dev04sa** [comment]
@tanay4768 , your folder structure still not updated.

**Comment by tanay4768** [comment]
updated folder structure

**Comment by dev04sa** [comment]
@tanay4768 , kindly look into your flutter project again.
Screenshot 2024-06-03 094847
there is no pubspec.yaml file . and your project will not gonna work without that file.

**Pull request closed without merging**
