### PR TITLE
crud task issue resolved

### PR DESCRIPTION
**Pull request by Nakulvarshney07**
Sorry sir for this. But i will try to learn github more deeply

### CODE REVIEW

**Comment by Nakulvarshney07** [comment]
photos and videos of the project are in readme.md

**Comment by dev04sa** [comment]
@Nakulvarshney07 , there is no video or photos present in readme .
and your code is also giving some error on web , try to resolve it.
Screenshot 2024-06-04 092342

**Comment by Nakulvarshney07** [comment]
Screenshot 2024-06-04 123156
sir photos and videos are present in the last file readme.md

**Comment by dev04sa** [comment]
@Nakulvarshney07 , Good work!!.
merging into main.

**Pull request merged**
